### ISSUE TITLE
Not really an issue - "/usr/lib/dpu.xclbin" not exist

### ISSUE THREAD

**Issue by nhphuong91** [Xilinx/aibox-reid#2]
I notice that the json configs ([crop.json](https://github.com/Xilinx/aibox-reid/blob/2021.1/config/crop.json), [draw_reid.json](https://github.com/Xilinx/aibox-reid/blob/2021.1/config/draw_reid.json), [reid.json](https://github.com/Xilinx/aibox-reid/blob/2021.1/config/reid.json)) refer to `"xclbin-location": "/usr/lib/dpu.xclbin"`. However, when I check that file on Kria Kv260 2021.1 image., there are no `dpu.xclbin` file there, but somehow the app still working normally.
Can anyone check it?

**Comment by xlnx-yuxiz** [comment]
Hi @nhphuong91 , you are so meticulous, yes, this field is not useful for these corresponding gstreamer elements, crop and draw didn't use any accelerator IP, and Reid use the DPU through Vitis ai library, which is also not affected by the xclbin-location, but has its own mechanism to find the DPU xclbin.
These confusing fields may be removed in a later release, thanks.
