### ISSUE TITLE
Error: docker pull xilinx/aibox-reid:latest

### ISSUE THREAD

**Issue by satoru-i** [Xilinx/aibox-reid#4]
I have set up the board according to xlnx_rel_v2022.1.
However, when I run "docker pull xilinx/aibox-reid:latest", I get the following error.

`Error response from daemon: pull access denied for xilinx/aibox-reid, repository does not exist or may require 'docker login': denied: requested access to the resource is denied'

Does "xilinx/aibox-reid" exist? If so, are there any other steps required, such as 'docker login'?

**Comment by xlnx-yuxiz** [comment]
can you try it again, it's published now, and now tag 2022.1 is added which is the same as the tag latest.
docker pull xilinx/aibox-reid:latest 
or
docker pull xilinx/aibox-reid:2022.1

**Comment by satoru-i** [comment]
Now I can exec "docker pull xilinx/aibox-reid:latest". Thank you!
