### ISSUE TITLE
Add Custom Model

### ISSUE THREAD

**Issue by neeloza-embrill** [Xilinx/aibox-reid#5]
Hi,

I want to use custom mode (.xmodel) in this AI Box with ReID Accelerated Application. I made changes as below but it is still running the internal ReID model.

`{
 "xclbin-location":"/lib/firmware/xilinx/kv260-aibox-reid/kv260-aibox-reid.xclbin",
 "ivas-library-repo": "/usr/lib/",
 "element-mode":"inplace",
 "kernels" :[
  {
   "library-name":"libivas_xdpuinfer.so",
   "config": {
     "model-name" : "yolov3_voc",
     "model-class" : "YOLOV3",
     "model-path" : "/opt/xilinx/share/vitis_ai_library/models/kv260-aibox-reid",
     "run_time_model" : false,
     "need_preprocess" : true,
     "performance_test" : false,
     "debug_level" : 2
   }
  }
 ]
`

Please suggest the necessary changes required in the configuration files.

Thanks.

**Comment by xlnx-yuxiz** [comment]
I think you are changing the refinedet.json, that will change the pedestrian detection model from refinedet to what you changed to, but then the reid will still be run.  We didn't provide customization of reid from json config file, in oder to achieve that, you need change the source code "src/ivas_reid.cpp"

**Comment by neeloza-embrill** [comment]
Is this possible to run only one model in this AiBox application like refinedet?

**Comment by xlnx-yuxiz** [comment]
It's not possible without modifying the code.
For your purpose please check the smartcam app.

**Comment by neeloza-embrill** [comment]
Thank you.
