### ISSUE TITLE
4 grids are not working on Petalinux 2021.1 with 4K monitor

### ISSUE THREAD

**Issue by neeloza-embrill** [Xilinx/aibox-reid#6]
Hi,

When I tested the AiBox-Reid application on Kria KV260, it could not display 4 RTST streaming on Petlainux release 2021.1. It is putting all 4 streaming in the first quadrant only (Position-0, Top left corner). I have validated that all RTSP camera input is 1080P.

It is perfectly working with Petalinx 2020.2 release. Will you please help me to resolve the issue?

Thanks!

**Comment by xlnx-yuxiz** [comment]
This is a known issue documented here: https://xilinx.github.io/kria-apps-docs/kv260/2021.1/build/html/docs/aibox-reid/docs/issue-aib.html 

`wget http://petalinux.xilinx.com/sswreleases/rel-v2021.2/generic/rpm/cortexa72_cortexa53/gstreamer1.0-plugins-bad-kms-1.16.3+git0+a3487d4884-r0.0.cortexa72_cortexa53.rpm`
`rpm -ivh --force ./gstreamer1.0-plugins-bad-kms-1.16.3+git0+a3487d4884-r0.0.cortexa72_cortexa53.rpm`

**Comment by neeloza-embrill** [comment]
This .rpm file is supported for Petalinux 2021.2 but it is not compatible with Petalinux 2021.1 release. Thank you for the quick response and for giving me hint.

For Petalinux 2021.1:
```
wget http://petalinux.xilinx.com/sswreleases/rel-v2021.1/generic/rpm/cortexa72_cortexa53/gstreamer1.0-plugins-bad-kms-1.16.3+git0+4cdc4b035f-r0.0.cortexa72_cortexa53.rpm
sudo rpm -ivh --force gstreamer1.0-plugins-bad-kms-1.16.3+git0+4cdc4b035f-r0.0.cortexa72_cortexa53.rpm
```
