### ISSUE TITLE
Couldnt allocate DMA allocator (tried using /dev/allegroIP)

### ISSUE THREAD

**Issue by neeloza-embrill** [Xilinx/aibox-reid#8]
Hi Team,

I am using this application for further development based on the application. I am not sure if this issue is related to the application or not. It will be great if you can provide the answer.

I am creating a Gstreamer pipeline to store camera output in an MP4 container.

* **Command**: 
```
sudo xmutil unloadapp
sudo xmutil loadapp kv260-aibox-reid
sudo gst-launch-1.0 -e rtspsrc location=rtsp://{usrename}:{password}@{IP}:{PORT}/stream1 !   application/x-rtp, clock-rate=90000,payload=96 !  rtph264depay ! h264parse  !  omxh264dec ! videoconvert ! omxh264enc  ! h264parse !  video/x-h264, profile=main  ! qtmux !  filesink  location=test.mp4
```

* **Output**:
```
Setting pipeline to PAUSED ...
[2022-11-06 11:55:02.622360290]	[omx_core.cpp:181]	[OMX_GetHandle]	Couldnt allocate dma allocator (tried using /dev/allegroIP)
ERROR: Pipeline doesn't want to pause.
ERROR: from element /GstPipeline:pipeline0/GstOMXH264Enc-omxh264enc:omxh264enc-omxh264enc0: Could not initialize supporting library.
Additional debug info:
../git/gst-libs/gst/video/gstvideoencoder.c(1636): gst_video_encoder_change_state (): /GstPipeline:pipeline0/GstOMXH264Enc-omxh264enc:omxh264enc-omxh264enc0:
Failed to open encoder
Setting pipeline to NULL ...
Freeing pipeline ...
```

As per my observation, /dev entry looks like as below.
```
xilinx-k26-starterkit-2021_1:~$ ls /dev/all*
/dev/allegroDecodeIP
```

Thanks

**Comment by xlnx-yuxiz** [comment]
@neeloza-embrill , aibox-reid firmware doesn't include encoder but just decoder, so please remove the encoder from your pipeline and try again. If you need encoder, please try with smartcam firmware.

**Comment by neeloza-embrill** [comment]
Hi @xlnx-yuxiz,

Thanks for letting us know. It is working without an encoder. Is there any way to add an encoder to this application?

**Comment by xlnx-yuxiz** [comment]
This platform doesn't have encoder, to add it you need to try to change the vivado project, but maybe the resources are not enough to do so. To try encoder you can use the firmware of smartcam.

**Comment by neeloza-embrill** [comment]
@xlnx-yuxiz , Thank you for helping.

I think smartcam application is not supporting RTSP input. Is there any other way to get RTSP input and use an encoder to store it in a container? Thanks!

**Comment by xlnx-yuxiz** [comment]
I see you are trying with your own pipeline, so you could just load the kv260-smartcam firmware, and try your pipeline, certainly you need necessary plugins installed which is easy by apt install.

**Comment by neeloza-embrill** [comment]
Hi @xlnx-yuxiz, Thanks for your support. You are a lifesaver. :)

**Comment by xlnx-yuxiz** [comment]
@xlnx-yuxiz You are welcome, please just help close this item if there's no further issue.

**Comment by Embeddedcoders** [comment]
Hi @xlnx-yuxiz.

Here, you have mentioned that resources are not enough. Can you please provide more information? Is it software limitation or hardware?

Thanks,
Neel

**Comment by xlnx-yuxiz** [comment]
I mean the FPGA hardware resources may not be enough to add the encoder. Current utilization is mentioned in this [page](https://xilinx.github.io/kria-apps-docs/kv260/2022.1/build/html/docs/aibox-reid/docs/hw_arch_accel_aib.html).

**Comment by karacanil** [comment]
Hey @xlnx-yuxiz
I'm having a similar issue on my KR260 board and I thought the "mv-camera" application firmware could solve my problem. What are the steps to include the files given [here](https://github.com/Xilinx/kria-apps-firmware/tree/xlnx_rel_v2022.1/boards/kr260/mv-camera)? Am I suppose to feed the ".bit" file through the "--fpga" option of  "petalinux-package"?

Thanks, best regards.
